# Numpy

Realizar operaciones matemáticas en Python puede ser complicado, ¿cómo podemos simplificarlo y operar con vectores o incluso matrices?

La respuesta es la librería **Numpy**.

Numpy es una biblioteca de Python que permite trabajar con arrays de manera eficiente. Se utiliza ampliamente en ciencia de datos para tareas como manipulación de datos, filtrado, transformaciones y visualizaciones. A continuación, se muestra un ejemplo básico de cómo usar Numpy para realizar operaciones matemáticas con vectores.

[https://numpy.org/](https://numpy.org/)


# En caso de que la librería no esté instalada, se puede instalar con **pip**

In [1]:
pip install numpy

Para utilizar Numpy, primero debemos importar la biblioteca. La convención habitual es importarla con el alias `np`.


In [2]:
import numpy as np

In [3]:
numeros = [1, 2, 3, 4]  # Creación de una lista de números

In [4]:
array = np.array(numeros)  # Creación del array de 1 dimensión a partir de la lista creada anteriormente

In [5]:
array  # Comprobación de que los datos dentro del array sean correctos


array([1, 2, 3, 4])

In [6]:
np.arange(0, 20, 2)  # Generación de los números del 0 al 19 de 2 en 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
np.random.randint(0, 100)  # Generación de un número aleatorio del 0 al 99

32

In [8]:
array = np.random.randint(0, 100, 10)  # Generación de 10 números aleatorios del 0 al 99

In [9]:
array

array([ 7, 58, 96,  7, 22, 52, 98, 36, 90,  5])

In [10]:
array.max()  # Mostrar el número con el valor más alto

np.int64(98)

In [11]:
array.argmax()  # Mostrar la posición del número con el valor más alto

np.int64(6)

In [12]:
array.min()  # Mostrar el número con el valor más bajo

np.int64(5)

In [13]:
array.mean()  # Mostrar el promedio


np.float64(47.1)

In [14]:
array[2]  # Obtener el valor en una posición determinada

np.int64(96)

In [15]:
array.reshape(5, 2)  # Mostrar el array en 5 filas y 2 columnas

array([[ 7, 58],
       [96,  7],
       [22, 52],
       [98, 36],
       [90,  5]])

In [16]:
array  # Pero es solo una visualización, no un cambio permanente

array([ 7, 58, 96,  7, 22, 52, 98, 36, 90,  5])

In [17]:
array = array.reshape(5, 2)  # Hacer el cambio permanente
array

array([[ 7, 58],
       [96,  7],
       [22, 52],
       [98, 36],
       [90,  5]])

In [18]:
array[3, 1]  # Acceder a un elemento en particular del array bidimensional

np.int64(36)

In [19]:
array2 = array[array > 30]  # Filtrar elementos mayores que 30
array2

array([58, 96, 52, 98, 36, 90])

# Tratamiento de valores NaN

**¿Qué es NaN?**

NaN es un valor especial que se utiliza para indicar la ausencia de datos. Dependiendo del tipo de datos, no siempre es posible usar un valor por defecto. Por ejemplo, si dejamos que el usuario introduzca **opcionalmente** una valoración numérica libre, no podemos usar el 0 (ni ningún otro número) para indicar que no ha introducido nad


In [20]:
array = np.asarray([np.nan, 2, np.nan, 3])
array2 = array.copy()

# Sustituir NaN por 0
array2[np.isnan(array2)] = 0
array2

array([0., 2., 0., 3.])